Repository datasaur-ai/robosaur, pull requests merged in 2023-03, with the labels that each got.

#88 #15807 - Improve message readability
  src/datasaur/rex/cancel-state.ts
Labels: enhancement

#90 implement new labelsets and remove a checkRecordStatus to prevent error
  sample/rex/config_rex.json
  src/handlers/auto-label.handler.ts
Labels: bug, enhancement

#91 /#15813 role reviewer
  sample/rex/config_rex.json
Labels: bug

#92 Fix invalid filename
  src/export/save-to-database.ts
Labels: bug, enhancement

#93 #16063 non root docker logs
  .gitignore
  build.sh
  on-premise/docker-compose.build.yml
  on-premise/scheme/default/add-channel.sh
  on-premise/scheme/default/docker-folder-template/.gitignore
  on-premise/scheme/default/docker-folder-template/consumers/.gitkeep
  on-premise/scheme/default/docker-folder-template/producers/.gitkeep
  on-premise/scheme/default/template.txt
  robosaur.Dockerfile
Labels: enhancement

#94 #16085 cancel in progress document recognition
  src/datasaur/rex/handle-project-creation-input-files.ts
Labels: enhancement
